# create-github-pr.ps1
# Automates the creation of a clean branch, committing changes, pushing, and generating a GitHub PR.
# Requires: git, gh (GitHub CLI)

$ErrorActionPreference = "Stop"

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$branchName = "apex/omnihub/v1.1.0-rc.1-investor-demo-$timestamp"
$commitMessage = "feat: v1.1.0-rc.1 Investor Demo Architecture & PWA Enhancements"
$prTitle = "🚀 Feature: AutoRep AI Investor Demo Readiness (v1.1.0-rc.1)"
$prBody = @"
## Overview
This PR consolidates all requirements for the upcoming Investor Demo into a fully production-ready, clean branch.

### Key Additions
- **Apple-Grade PWA Ecosystem**: Full mobile offline support and native iOS feel.
- **KPI Manager Dashboard**: Recharts-based telemetry integration.
- **Demo Simulator Engine**: Invisible simulation orchestration hotkey via 'use-store.ts'.
- **Premium UX Motions**: SplashScreen orchestration and Tailwind Keyframes.
- **Documentation**: Professional CHANGELOG.md implemented.

*Generated by APEX-Antigravity.*
"@

Write-Host "Starting Git/GitHub Automation..." -ForegroundColor Cyan

Write-Host "Creating branch $branchName..."
git checkout -b $branchName

Write-Host "Staging files..."
git add .

Write-Host "Committing changes..."
git commit -m $commitMessage

Write-Host "Pushing branch to remote..."
git push -u origin $branchName

Write-Host "Creating GitHub Pull Request..."
$prUrl = gh pr create --title $prTitle --body $prBody --head $branchName --base main

Write-Host "`nSUCCESS: PR Created Successfully!" -ForegroundColor Green
Write-Host "PR Link: $prUrl" -ForegroundColor Yellow
Write-Host "Please use this link for review and approval."
