// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sijqccfsvrvgujgkkwuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpanFjY2ZzdnJ2Z3VqZ2trd3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzMjcyNjMsImV4cCI6MjA5MDkwMzI2M30.a_AH6_2OjJozUQZfGD9v-JYxBBNAs0falnT68-IyUZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});